/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.dundee.computing.sensorweb.servlets;
import uk.ac.dundee.computing.aec.sensorweb.lib.Web;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author andyc
 */
@WebServlet(name = "PostTest", urlPatterns = {"/PostTest"})
public class PostTest extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String url="http://localhost:8080/SensorWeb/Translate";
        String Data="b64History=\"{\"b64History\":\"AwADWQAL0vQAAD6+AA4DhAH5BaIAKwHCAYADmAH7B3gAKwHDAX0DmAHACtMAKwG1AX4DmAHEEVUAKwG0AX8DmAHFDS0AKwGyAX0DmAHLCUAAKwG0AX8DlwHCJ5MAKwGyAX8DmAGuIckAKwGtAX4DlwGvHL8AKwGsAX8DlwGwJ3kAKwGrAX8DlwGnTpQALAGoAXwDlwGm//8ALAGnAX4DlwGs//8ALAGpAX8DlwGo//8ALAGnAXsDlwGj//8ALAGlAX0DlgGf//8ALAGkAX0DlwGc//8ALQGkAX0DlwGf//8ALQGjAXwDlwGg//8ALQGjAX8DlgGd//8ALgGjAX8DlgGf//8ALgGkAX0DlwGj//8ALgGlAX0DlwGj//8ALgGkAXwDlgGj//8ALwGkAX8DlgGl//8ALwGkAX8DlgGm//8ALwGkAX0DlgGl//8ALwGkAX4DlwGj//8ALwGkAYEDlgGk//8ALwGjAYEDlgGk//8ALwGjAX0DlgGi//8ALwGjAX0DlQGf//8ALwGkAX0DlgGg//8ALwGjAX8DlgGg//8AMAGjAYADlgGf//8ALwGjAX8DlgGf//8AMAGiAX8DlgGc//8AMAGiAYADlgGc//8AMAGiAX0DlgGb//8AMAGiAX0DlgGZ//8AMQGiAYEDlgGa//8ALwGhAX4DlgGb//8ALwGhAX8DlgGZ//8ALwGgAX0DlQGY//8AMAGgAX8DlQGX//8AMAGgAYEDlgGW//8ALwGfAX4DlgGV//8AMAGfAX8DlgGV//8AMAGfAX8DlQGU//8AMAGeAX4DlQGT//8AMAGeAX4DlAGU//8AMAGeAX4DlQGS//8AMAGdAX4DlQGR//8AMAGdAX4DlQGR//8AMAGcAX8DlQGS//8AMAGcAX4DlQGS534AMAGdAXsDlQGSVzoAMAGcAX8DlQGTM2gAMAGcAYEDlQGVHvkAMQGdAXwDlQGXFtwAMQGeAX0DlQGbEX0AMQGfAX0DlQGfDyQAMQGgAX8DlQGhDQQAMQGhAX8DlQGjC7QAMQGiAX4DlQGqCUMAMQGkAYADlQGuCKUAMQGmAX0DlQGsCz0AMAGmAX8DlQGnDG8AMQGkAXsDlAGjEwMAMQGiAXsDlQGgEtYAMAGgAXsDlAGjEbEAMQGgAYADlAGoDjQAMQGiAXsDlQHABkYAMQGoAX4DlAGtELAAMQGlAXwDlAGzCXsAMAGlAX8DlAG4C2MAMQGmAX4DlAHIBR0AMAGsAX4DlAHXA/MAMAGyAXwDlQHcBBcAMAG2AX4DlQHfBV8AMAG4AXsDlAHjA8cALwG5AXsDlAHcBooALwG5AX0DlAHqA78ALwG8AX8DlAHsA+MALwG+AXwDlAHuA9UALwHAAXkDlAH0A8kALgHBAX0DlAH3BCQALgHEAXsDlAHuBNQALQHBAXoDlAH8BFcALQHGAXkDlAH1BOYALQHEAX8DlAHtBY8ALQHCAXsDlAHqBhUALQHBAX0DlAHhBssALAG9AXsDlAHkBlkALAG/AXsDlAILBXQALAHDAX4DlAH+BZgALQHJAXkDlAHnDNUALAHEAXsDlAHmBpwALAHAAXsDlAHoCscALAHAAXwDkwHjCh0AKwG/AXsDlAHmCTUAKwG/AX4DlAHgDNkAKwG+AXwDkwHaGSIAKgG7AXoDlAHYGR8AKgG6AXoDlAHQIpIAKwG5AXsDkwHJLyIAKgG3AXwDlAHEjSUAKwG1AX4DkwHC//8AKwG1AXwDlAHA//8AKwG0AX0DkwG9//8AKwGzAXwDkwG9//8AKwGyAXoDkwG+//8ALAGxAXwDkwG7//8ALAGxAXsDkwG4//8AKwGxAXkDkwG3//8AKwGwAXkDkwG1//8AKgGvAX0DkwG0//8AKgGvAXkDkwGy//8AKgGvAXsDkwGx//8AKgGuAXwDkwGv//8AKgGuAXkDkwGu//8AKgGsAXsDkwGw//8AKgGqAXwDkwGw//8AKgGrAXsDkwGt//8AKgGqAXoDkwGs//8AKgGrAXoDkgGq//8AKgGqAXwDkwGp//8AKgGqAXkDkwGo//8AKgGpAXwDkgGm//8AKgGpAXoDkgGl//8AKgGpAX4DkgGk//8AKgGoAX0DkgGl//8AKgGnAXsDkgGk//8AKgGnAXsDkgGk//8AKgGoAXkDkgGj//8AKgGnAXsDkgGi//8AKgGnAXoDkQGh//8AKgGnAXwDkgGf//8AKwGmAXkDkgGd//8AKwGmAXoDkgGc//8AKwGlAXoDkgGc//8AKwGkAXwDkgGd//8AKwGlAXwDkgGc//8AKwGlAXsDkgGd//8AKwGkAXsDkgGc//8AKwGjAX0DkgGd//8AKwGjAX4DkgGe//8AKwGjAXwDkgGd//8AKwGjAXoDkgGb//8AKwGjAX0DkQGb//8AKwGiAXkDkgGa//8AKwGiAXsDkgGau7sAKwGiAXoDkgGaRuAAKwGiAXoDkQGbL/oALAGiAXkDkQGdH/oALAGjAX4DkQGfHh8ALAGkAXwDkQGhE0YALAGlAXwDkQGkDpwALQGmAXwDkQGoC48AKwGnAXoDkgGlDIYAKwGnAX4DkQGfEKQALAGkAXwDkQGdFDMAKwGjAXkDkQGtC7QALAGoAX4DkQGyCpEALAGpAXoDkQGmEx8ALAGmAXwDkQG1DlkALAGqAXoDkQG0D6kAKwGrAXkDkQGyEfwAKwGpAXwDkQGzEEoAKwGpAXsDkQHBCEoALAGsAXoDkQHDC9YAKwGuAXkDkQHOBqgAKwGyAXsDkQHOCpIAKwGzAXsDkQHhBJoAKwG4AXoDkQHcB7EAKgG6AX0DkQHaBOYAKgG4AXwDkQHXBwcAKQG4AXsDkQHXB9UAKgG5AXwDkQHSC4wAKgG4AXoDkQHTCSwAKQG4AXkDkAHcBZAAKQG7AXoDkQHlBQQAKQG/AXgDkQHmBS4AKQHAAXgDkQHkCCkAKAG/AXkDkQHcCzUAKAG9AXoDkQHgCooAKAG+AXoDkQHeDocAKAG/AXwDkAHrCqEAKAHBAXgDkAHyB/UAKAHFAXoDkQH4BbUAKAHIAXoDkQH7A9sAKAHJAXsDkQHrDtAAJAHGAXkDkAHsDIoAIQHFAXoDkAHwB84AHwHIAXYDkQHvCjkAHwHJAXYDkQHtDCwAHwHHAXoDkAHoC/cAHwHGAXoDkAHpD5YAHwHHAXkDkAHkGtcAHwHGAXcDkAHgJ5UAHwHEAXoDkAHeHucAHwHDAXgDkAHYLWMAHwHCAXsDkAHTSlMAHwHAAXoDkAHRp3YANAG/AXsDkAHL//8AIAG9AXoDkAHE//8AIAG7AXkDkAHE//8AIAG6AXwDjwHC//8AIAG5AXsDkAHA//8AIAG3AXgDkAG6//8AIQG2AXgDkAG7//8AIAG1AXsDjwG4//8AIAG1AXYDkAGz//8AIAGzAXgDkAGw//8AIQGyAXsDkAGl//8AIQGvAXsDkAGh//8AIQGsAXkDjwGs//8AIQGuAXgDjwGr//8AIQGuAXoDjwGp//8AIQGuAXoDjwGo//8AIQGtAXkDjwGq//8AIQGsAXoDjwGo//8AIgGtAXkDjwGm//8AIgGrAXoDjgGm//8AIgGqAXcDjwGm//8AIgGpAXoDjwGi//8AIgGoAXoDjwGg//8AIwGmAXcDjwGc//8AIgGmAXsDjgGc//8AIgGkAXoDjwGd//8AIwGkAXgDjwGb//8AIwGjAXkDjgGd//8AIwGkAXgDjwGc//8AIwGjAXoDjwGc//8AIwGjAXoDjwGi//8AIwGjAXgDjwGj//8AIwGjAXoDjwGl//8AIwGkAXoDjwGi//8AIwGkAXgDjgGe//8AIwGjAXkDjwGi//8AIwGjAXgDjwGp//8AIwGlAXoDjgGr//8AIgGmAXwDjwGr//8AJQGmAXoDjwGv//8AJQGoAXwDjwGv//8AIgGpAXoDjwGw//8AIgGqAXcDjwGw//8AIgGqAXkDjgG2xlMAIgGsAXoDjwG4apAAIgGtAXoDjgG1PR8AIQGtAXoDjgG4LBIAIQGtAXgDjgG5IZEAIQGuAXsDjgHBEfkAIQGxAXoDjgHNDdQAIQG1AXsDjgHVCqAAIQG5AXoDjgHWB1gAIAG7AXoDjgHSCbEAIAG6AXgDjgHMENMAIAG4AXgDjgHHFOAAIAGzAXUDjgHLCXYAIAG0AXgDjgHMFM8AHwG1AXkDjgHNDSEAHgG0AXYDjgHPCPEAHgG1AXgDjgHMBrAAHgGzAXYDjgHQB/wAHgG1AXkDjgHSCGsAHQG2AXgDjgHMEOcAHQGzAXYDjgHNB6EAHQGzAXYDjgHYBf0AHAG3AXoDjgHZBWEAHAG3AXgDjgHRCG4AHAG1AXgDjgHVBJIAGwG1AXYDjgHSCh0AGwG1AXcDjgHACRcAGwGsAXYDjQHJBj4AGwGvAXUDjQHHBTsAGwGvAXUDjQHQBoYAGwGyAXgDjQHLCMUAGwGxAXkDjQHABj8AGgGrAXgDjQHCBqkAGgGrAXcDjQHSBvsAGgGzAXYDjQG9Ds8AGgGrAXYDjQG4DW4AGgGoAXkDjQHBCI8AGgGrAXcDjQHIBCoAGgGrAXQDjQHDA7wAGQGoAXYDjQHCBe0AGQGoAXQDjQG5BaQAGQGlAXUDjQG7BTAAGQGkAXUDjQG6BbsAGAGkAXUDjAHKBj4AGAGrAXMDjQGwEAwAGAGkAXcDjAGrCvwAGAGgAXYDjQGoDYIAGAGeAXMDjQG+ClMAGAGjAXUDjAHLDLMAGAGqAXYDjAHCDlkAGAGoAXcDiwG4GqUAGAGoAXYDjQGpcMQAGAGiAXUDjAGh2+EAGAGcAXgDjAGd//8AGAGaAXUDjAGZ//8AGAGaAXcDjAGW//8AGAGZAXYDjAGT//8AGAGXAXYDjAGL//8AGAGTAXUDjAGJ//8AGAGQAXcDjAGG//8AGAGSAXgDjAGD//8AGAGRAXcDjAGB//8AGAGQAXcDjAF///8AGQGPAXUDjAF7//8AGQGOAXkDiwF9//8AGQGNAXgDjAF9//8AGQGNAXcDjAF5//8AGQGNAXcDjAF3//8AGQGLAXoDiwF3//8AGQGLAXcDiwF7//8AGQGMAXcDjAF6//8AGgGMAXkDiwF6//8AGgGMAXgDiwF6//8AGgGLAXkDjAF5//8AGgGLAXUDjAF3//8AGgGLAXcDiwFz//8AGgGKAXYDiwFw//8AGwGKAXYDiwFe//8AGwGFAXgDiwFb//8AGwGEAXQDiwFj//8AHAGFAXUDiwFm//8AHAGFAXgDiwFq//8AHAGFAXcDiwFn//8AHAGFAXcDiwFr//8AHAGEAXYDiwFq//8AHAGFAXgDiwFo//8AHAGFAXQDiwFo//8AHAGDAXgDiwFh//8AHQGEAXUDiwFd//8AHQGCAXcDiwFY//8AHQGBAXUDigFY//8AHQGAAXoDiwFZ//8AHQGAAXgDiwFb//8AHQGAAXcDiwFg//8AHQGCAXkDigFe//8AHgGCAXgDigFd//8AHQGAAXUDigFegH8AHgGBAXcDigFiRVgAHgGCAXYDiwFmLwcAHgGEAXgDigFjJDAAHgGDAXoDigFqFD8AHgGEAXkDiwFwGWAAHgGIAXYDigFqGCYAHgGGAXYDigFwDPwAHwGHAXcDigF8DCIAHwGLAXgDiQF2FqgAIAGKAXYDigFzFlMAHwGJAXYDigF6DBgAHwGKAXgDigGRClsAIAGRAXcDiwGEES0AHwGPAXgDigGZBuMAHwGUAXcDigGjBhUAHwGZAXkDigGqBesAHwGcAXcDigGvBhYAHwGfAXcDigGxBz0AHwGfAXUDigG5BhsAHwGjAXcDigGyB84AHwGiAXcDigG5BkYAHwGkAXUDigGyBy4AHwGiAXUDigHBBfIAHgGmAXcDigHEBTMAHgGoAXkDigHIBRUAHgGrAXYDigHEBPcAHgGqAXYDigHJBLYAHQGtAXcDigHNBEEAHQGuAXYDigHOBFkAHQGwAXYDiQHNBPUAHAGvAXcDigHOBIMAHAGwAXUDigHOBVwAHAGwAXQDigHMBTQAHAGxAXQDigHOBMEAGwGxAXYDigHHBy0AHAGwAXUDigHNBy4AHAGyAXQDigHFB+kAGwGwAXUDigHIBmsAGwGwAXUDigHICNYAGwGwAXUDigHPBxkAGwGyAXUDigHGDPkAGwGxAXYDigHADRUAGwGuAXYDigG+FMAAGwGuAXcDigG4FS8AGwGtAXMDigGyJrgAIAGsAXYDigG1EOUAGwGsAXIDigHMDRIAGwGxAXYDigHEFjUAGwGyAXMDiQHGEqIAGwGwAXQDigHAHuoAGgGwAXMDigGwO/AAGgGrAXIDiQGljxUAGgGoAXMDiQGc//8AGgGkAXMDiAGU//8AGwGhAXMDiQGX//8AGwGhAXUDiQGW//8AGwGhAXYDiQGb//8AGwGiAXYDiQGU//8AGwGhAXQDiQGT//8AGwGgAXYDiQGV//8AGwGhAXQDiQGZ//8AGwGhAXYDiQGc//8AGwGiAXUDiQGc//8AGwGjAXYDiQGc//8AGwGjAXQDiQGb//8AGwGjAXUDiQGZ//8AGwGiAXcDiQGS//8AHAGgAXgDiAGQ//8AHAGfAXYDiQGT//8AHAGfAXQDiQGP//8AHAGeAXQDiQGU//8AHAGfAXgDiAGX//8AHAGhAXQDhwGW//8AHAGgAXQDiQGV//8AHAGgAXYDiQGW//8AHAGhAXQDiQGW//8AHAGgAXYDiQGW//8AHAGgAXgDiAGV//8AHAGgAXYDiQGS//8AHAGfAXYDiAGR//8AHAGfAXcDiAGS//8AHQGfAXUDiAGT//8AHAGfAXYDiQGT//8AHQGfAXYDiAGT//8AHQGfAXcDiAGU//8AHQGfAXcDiAGU//8AHQGfAXgDiAGR//8AHQGeAXUDiAGN//8AHQGdAXUDiAGM//8AHQGcAXgDiAGK//8AHQGbAXUDiQGL//8AHQGcAXcDiAGK//8AHQGbAXgDiAGK//8AIgGbAXUDiAGH//8ALwGaAXUDiAGH//8AIAGaAXcDiAGGgSsAJAGaAXQDiAGKP0MAIAGaAXgDiAGPKeYAIAGcAXcDiAGWGe4AIAGfAXYDiAGZFWoAIAGgAXcDiAGfELsAIAGiAXYDiAGkDzYAIAGkAXcDiAGrC4oAIAGmAXcDiAGzCzIAIAGpAXcDiAG5CTsAIAGsAXgDiAG/B8MAIAGuAXUDiAHECA4AIAGwAXUDiAHGB+wAIAGyAXYDiAHIB20AIAGyAXgDiAHNBlkAHwG1AXcDiAHWBZIAHwG4AXYDiAHZBakAHwG6AXcDiAHeBXwAHwG7AXUDiAHjBREAHgG9AXYDiAHrBJAAHgHAAXMDhwHvBC0AHQHCAXMDiAHkEoEAHQHBAXYDiAHaB6QAHQG8AXYDiAHWDnEAHQG8AXQDiAHSGV8AHQG6AXcDhwHVCgIAHQG7AXUDiAHkBk4AHQG/AXYDhwHhCnUAHQHAAXIDiAHhCOgAHAHAAXIDiAHfCfAAHAG/AXYDiAHnB/EAHAHCAXQDiAHsB0EAHAHEAXYDiAH6BDEAHAHHAXYDiAH+BtMAGwHMAXIDiAHlFK0AGwHFAXcDiAHcDUAAGwHBAXYDhwHcCO4AGwHBAXUDiAHvBTwAGwHGAXUDhwIEBHYAGgHNAXUDhwIGBagAGgHOAXUDhgH5CnoAHwHMAXYDiAHrGqIAGgHIAXMDhwHfHxcAGgHEAXMDiAHfGaYAGgHDAXUDhwHeGBYAGgHDAXQDhwHdD5IAGgHDAXQDhwHeDacAGQHDAXMDhwHaEXkAGQHCAXMDhwHVHjUAGQHAAXYDhwHRJGYAGQG/AXMDhwHNWUEAGQG9AXcDhwHJmFUAGgG8AXIDiAHG//8AGgG7AXYDiAHE//8AGgG6AXIDiAHC//8AGgG5AXUDhwHC//8AGgG5AXMDhwHD//8AGgG4AXIDhwHD//8AGgG4AXIDhwHC//8AGgG4AXIDhwG///8AGgG3AXMDhwG///8AGgG3AXQDhwG+//8AGgG3AXMDhwHB//8AGgG3AXQDhgG8//8AGgG3AXIDhwG3//8AGgG1AXYDhwG5//8AGgG1AXQDhwG1//8AGgGzAXQDhwG0//8AGgGzAXUDhwGq//8AGgGxAXYDhwGn//8AGgGvAXYDhgGg//8AGgGtAXUDhwGj//8AGgGtAXQDhwGi//8AGwGtAXQDhwGk//8AGwGuAXUDhwGm//8AGwGvAXMDhwGo//8AGwGvAXMDhwGg//8AGwGtAXMDhgGb//8AGwGrAXcDhgGc//8AGwGrAXQDhwGT//8AGwGpAXQDhwGO//8AGwGmAXMDhwGN//8AGwGlAXUDhgGJ//8AGwGkAXUDhgGG//8AHAGiAXMDhwGD//8AHAGhAXMDhgGE//8AHAGhAXUDhQGC//8AGwGgAXQDhgGC//8AHAGfAXMDhwGC//8AHAGfAXUDhgGD//8AHAGfAXYDhgGD//8AHAGfAXYDhgGD//8AHAGfAXMDhQGE//8AHQGfAXMDhgGD//8AHAGfAXYDhQGC//8AHQGeAXYDhgGB//8AHQGeAXYDhgGDXbwAHQGeAXQDhgGHKE8AHgGfAXUDhgGNHwkAHgGhAXUDhgGRHfYAHgGjAXUDhgGUGLQAHgGkAXUDhgGfD7cAHgGmAXUDhgGqDWIAIAGqAXYDhgGvD3oAIAGsAXQDhgGzDWkAHwGtAXYDhgG6CqIAHwGwAXcDhgG+DNwAHwGxAXQDhgG+DEsAHwGyAXUDhgHDCwEAHwG0AXYDhgHJCkQAHwG2AXMDhgHQChcAHwG4AXIDhgHXB2sAHwG7AXUDhgHoBlYAHwHAAXMDhgH4BQoAHgHGAXYDhgH9BVgAHgHJAXUDhgIDBUwAHQHNAXIDhQIBBVIAHQHNAXYDhgH3BkkAHQHMAXEDhgHzBgAAHAHLAXIDhQHyBTEAHAHLAXIDhQHsBTMAHAHKAXMDhgHzBTYAGwHMAXMDhgH8BLEAGwHPAXYDhgILBLYAGwHUAXYDhgIcBMgAGgHaAXUDhgIhBBwAGQHcAXIDhgIuA94AGQHhAXIDhgIrA+UAGAHiAXMDhgIrBOcAGAHjAXQDhgIgBS8AGAHhAXUDhgIeBQsAGAHhAXIDhQIiBPMAFwHiAXIDfwIqBmsAFwHjAXIDhgI7CE8AFwHmAXQDhgI/BdQAFgHrAXQDhgJWBPMAFgHvAXQDhgJVCFwAFQHvAXEDhgJBCHMAFQHuAXQDhgJNBV4AFAHzAW8DhgJIBl8AFAHyAXIDhgJOBzYAFAH0AXQDhgJKCZEAFAHyAXIDhgJJCmIAEwHzAXMDhgJBDHgAEwHyAXQDhgIPGBkAEwHkAXADhgIBIX8AEwHeAXMDhgH7KFMAFAHbAXIDhgH2WAUAFAHYAXIDhgH8rWQAFAHYAXIDhgH6//8AFAHYAXIDhQH4//8AFAHXAXQDhgHv//8AFAHVAXEDhgHo//8AFAHTAW8DhgHn//8AFAHSAW8DhgHl//8AFAHRAXIDhgHl//8AFAHRAXQDhQHn//8AFQHRAXADhgHv//8AFAHSAXIDhQH+//8AFAHVAXEDhQIB//8AFAHXAXADhQIB//8AFAHYAXIDhQH3//8AFAHWAXADhQH4//8AFAHWAXIDhQH2//8AFAHVAXMDhgH9//8AFAHWAXQDhgIO//8AFAHbAXQDhgIM//8AFAHbAXMDhQH6//8AFAHZAXADhQHn//8AFAHTAXEDhQHh//8AFAHRAXMDhQHg//8AFAHQAXQDhQHi//8AFAHRAXQDhQHq//8AFAHRAXMDhgH5//8AFAHWAXMDhQIC//8AFAHaAXADhQIE//8AFAHcAW8DhQIC//8AFAHdAXMDhQIC//8AFAHcAXQDhQIF//8AFAHeAXEDhQIF//8AFAHeAXADhQIE//8AFAHeAXEDhQID//8AFAHfAXEDhQID//8AFAHfAXIDhQIH//8AFAHhAXADhQH///8AFAHfAXEDhQH9//8AFAHfAXADhQHw//8AFAHbAXEDhQHt//8AFAHYAXEDhQHs//8AFAHXAXQDhAHm//8AFAHWAXIDhQHf//8AFAHSAXIDhQHg//8AFAHSAXEDhQHcfD0AFQHQAXMDhQHhYTIAFAHSAXEDhQHkMssAFQHTAXQDhQHiNBcAFQHSAW4DhQHjKRkAFQHSAXEDhQHfIa4AFQHRAXADhQHcII8AFQHQAW8DhQHpCjoAFQHSAW8DhQHyCzUAFAHWAXQDhQH0DEgAFAHYAXQDhQHtF5MAFAHXAXEDhQHjFzgAFAHSAXADhQHiFgEAFAHQAW8DhQH1BaMAFAHWAXIDhAIAClYAFAHbAXADhQHuESkAFAHYAW8DhAHvCtcAEwHVAXIDhQH1BUkAFAHWAXIDhQHwDeUAEwHWAXMDhQH4BbMAFAHYAW8DhQIBBkgAEwHcAW8DhQHvESsAEwHWAXEDhAH2B18AEwHXAXMDhQIABPgAEwHaAXEDhQIDBnYAEwHdAW4DhQHwDm8AEwHXAXEDhAHwDE0AEwHWAW8DhAHyElQAEwHZAXADhAHrE0IAEwHUAXEDgwH3DhgAEwHWAW8DhQH7EmAAEwHZAXADhQHxEnQAEwHWAXEDhAICB8sAEwHaAW4DhAH4CNEAEgHaAW0DhAH4BKsAEgHaAXADhAH6BY0AEgHbAXADhQH/CWwAEgHcAXIDhQIOCMAAEgHhAW8DhAIHDUwAEgHhAW4DhAIVBkQAEgHjAXADhAIjBNwAEQHnAW8DfgIKDPAAEQHhAW8DhAIGDksAEQHgAW4DhQIXBlAAEAHjAXADhQH+EPkAEAHfAWwDhAIOCQ8AEAHgAW8DhAIVCfcAEAHjAXADhAIJEGoAEAHhAXADhAIOD0MAEAHiAW4DhQH+Fq0AEAHfAXEDhAH7IjAAEAHcAW8DhAHrL8MAEAHXAWwDhAHiZD8AEAHUAXEDhAHZ//8AEAHPAXADhAHS//8AEQHNAW0DhAHO//8AEQHLAW0DgwHG//8AEQHIAWwDgwHE//8AEQHHAW8DhAG///8AEQHFAXEDgwHD//8AEgHFAXADhAG9//8AEgHEAXEDhAG2//8AEgHCAXADhAG4//8AEgHBAW8DhAG2//8AEgHAAW8DgwG0//8AEgG/AXADhAGy//8AEgG/AW0DhAGt//8AEgG9AXIDhAGs//8AEwG8AW4DhAGq//8AEwG8AW0DgwGn//8AEwG7AW4DhAGl//8AEwG6AXADhAGk//8AEwG5AW4DhAGi//8AEwG4AXIDgwGe//8AEwG3AXADhAGU//8AFAG1AXIDhAGO//8AFAGyAXADggGS//8AFAGyAXIDgwGV//8AFAGzAXIDgwGV//8AFAGzAXADgwGS//8AFAGyAXADgwGP//8AFQGxAW8DgwGS//8AFQGxAW4DgwGU//8AFQGyAXEDgwGR//8AFQGxAXADgwGM//8AFQGvAXMDgwGF//8AFgGsAW0DgwGA//8AFQGrAW8DgwGC//8AFQGqAXADgwGF//8AFQGqAW8DgwGF//8AFgGrAXMDgwGB//8AFgGpAXEDgwGH//8AGgGqAW0DgwGH//8AGAGqAXEDgwGH//8AGAGqAXIDgwGH//8AGAGqAW4DgwGH2EoAGAGqAW8DgwGLZl4AGQGrAW8DgwGLP7AAGQGrAW0DggGML9YAGQGrAXEDggGNIr0AGQGsAXIDgwGTIiwAGQGtAXEDgwGWHd4AGgGuAXEDgwGdGV4AGQGvAXIDggGjFiAAGQGyAXIDgwGrELcAGQG0AW8DgwGxDg8AGQG3AW8DgwG3C6UAGQG5AW8DggG7CgUAGQG7AXIDgwG8DEcAGQG8AW0DgwHBC6AAGQG8AXIDgwHJCe8AGQG/AXADgwHNCo8AGQHAAW4DggHVCaAAGQHDAW8DgwHYCiwAGQHEAW8DggHXDmoAGQHFAXADgwHYDpYAGQHFAW0DgwHbDfoAGAHFAW8DggHfED0AGAHGAW8DggHiDtYAGAHIAW8DfwHmD+UAGAHIAXEDggHwDOMAGAHMAW8DggHzDLAAFwHOAW8DggH3EEYAFwHQAW4DggH4FZQAFwHPAW8DggH3Ev0AFwHQAWwDggH9EMAAFgHSAW4DgQIIDVoAFgHWAWwDggIMEIcAFgHZAW0DggIPB+0AFQHZAW0DggITCgcAFQHcAWwDggIQDUAAFAHdAWsDggIWDUwAFAHfAW4DggIgCT8AEwHiAXADggIoC1kAEgHlAW0DggIfDMIAEgHlAW0DggIzCbUAEgHmAW4DggI4CmwAEQHqAWwDggIwDU0AEAHrAXADggIzDT8AEAHsAWwDggI+C0UAEAHvAWoDggJDC1gADwHxAW0DggJFCvoADwHzAW0DggJJCrEADwH1AW0DggJQC5IADgH4AW0DggJMDT8ADgH4AWoDggI3FM8ADgH0AWwDggIVI1wADgHqAWwDggIHMYMADgHjAWoDggHzb+MADgHdAWsDggHn//8ADwHYAWsDggHf//8ADwHUAWsDggHZ//8ADwHRAWsDggHS//8ADwHOAWsDggHN//8ADwHMAWsDggHJ//8AEAHLAW8DggHH//8AEAHHAWwDggHC//8AEAHGAW0DgQG9//8AEAHFAWwDggG4//8AEAHDAWwDggG4//8AEAHCAW0DgQG1//8AEQHBAW8DggGy//8AEQHAAW0DgQGz//8AEQG/AW8DggG3//8AEQHAAW0DgQG2//8AEQHAAWsDgQGy//8AEQG/AWoDggGw//8AEgG/AW4DgAGv//8AEgG+AW0DgQGu//8AEgG9AW8DgQGr//8AEgG8AW4DggGp//8AEwG8AW4DgQGn//8AEgG6AW0DgQGj//8AEgG5AWwDgQGn//8AEgG6AWwDgQGp//8AEgG6AXADgQGq//8AEgG6AW8DgQGo//8AEgG6AWwDgQGl//8AEgG5AW4DgQGk//8AEgG5AXADgQGh//8AEgG4AW4DgQGh//8AEwG3AW4DgAGn//8AEwG5AW8DgQGq//8AEgG6AW4DgQGq//8AEwG6AXADgQGq//8AEwG5AW4DgQGo//8AEwG5AWoDgQGn//8AEwG4AW4DgQGi//8AEwG3AWsDgAGi//8AFAG3AW4DgQGn//8AFAG3AW0DgQGi//8AFAG2AW8DgAGa+KIAFAG0AW4DgQGZfWIAFAGzAW4DgQGaRuAAFAGzAXADgQGfMEEAFAG1AW8DgQGlISAAFAG3AWwDgAGuG8oAFAG5AW4DgQGvHtUAFQG5AXADgQG0EXoAFAG6AW0DgQG9DgkAFAG+AW0DgQG6F+YAFAG9AW0DgQG6GyEAFAG9AWwDgQG+FDIAFAG+AWwDgQHFEjkAFAHAAW0DgQHOEs8AFAHDAWwDgQHaD7IAFAHGAWsDgQHoDEQAFAHMAWwDgQHwDS0AEwHPAW8DgQHtENgAEwHQAW0DgQHvFKAAEwHRAW0DgQHuGakAFQHRAWsDgQHzGTUAEgHTAWwDgQH2F1IAEgHUAWwDgQH8DugAEQHYAWkDgQH6FNEAEQHZAW8DgQH6Ee0AEQHXAWwDgQIACyoAEQHaAWwDgAISBawAEAHfAWwDgQIMFqIAEAHhAWwDgAILFj4AEAHfAWsDgQIPFWkADwHhAW0DgQIVFm0ADwHjAW4DgQIVFXQADwHjAWwDgQIUECQADwHkAWoDgQIZFn4ADgHmAWkDgQIcFccADgHoAWoDgQAAAAAAAAAAAAAAAAAA\",\"startupTime\":\"Mon Mar 30 15:48:02 BST 2020\"}\"";
      Web.PostJson(url, Data);
        
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet PostTest</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet PostTest at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
